[package]
name = "koicore"
version = "0.1.0"
edition = "2024"

[dependencies]
unescaper = "0.1"
regex = "1.0"
nom = "8.0"
encoding_rs = "0.8"
nom-language = "0.1.0"
nom-supreme = "0.8.0"

[workspace]
members = [
    "koicore_ffi",
]
