[package]
name = "koicore_py"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
koicore = { path = "../.." }
pyo3 = { version = "0.26", features = ["extension-module", "abi3", "abi3-py310"] }