[package]
name = "koicli"
version = "0.1.0"
edition = "2024"
authors = ["Ovizro <ovizro@visecy.org>"]

[dependencies]
koicore = { path = "../..", features = ["serde"] }
clap = { version = "4.4", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
